name: Build Workflow

on:
  pull_request:
    types: [closed]

jobs:
  build-windows:
    if: github.event.pull_request.merged == true
    runs-on: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run cx_Freeze
        run: |
          python setup.py build
      - name: Zip
        run: |
          Compress-Archive -Path "build/exe.win-amd64-3.9/*" -DestinationPath PySN.zip
      - uses: actions/upload-artifact@v3
        with:
          name: PySN.zip
          path: PySN.zip
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.1.0
          release_name: v1.1.0
          body: |
            Refactored with functions! This should be a bit cleaner under the hood, relatively speaking. It should also be a bit easier to wrap this in a GUI at some point.

            Changes:
            - PySN now automatically detects which console your game is for. This should speed up searches compared to looking for updates across all 3 consoles.
            - I've added some spacing to the outputs, which makes things easier to read in my opinion.
            - Error handling has been improved.
            - cx_Freeze now creates license file automatically, as the license terms require that it be included with any program built/"frozen" with cx_Freeze.
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: PySN.zip
          asset_name: PySN.zip
          asset_content_type: application/zip